Evg/models
burunyuu23/ratingus-backend pull request #1
Opened 2024-03-29 16:29 UTC by PiPuKaPRo

2024-03-29 16:35 UTC, PiPuKaPRo commented
добавил инит для БД

2024-03-29 19:03 UTC, burunyuu23 requested changes

2024-03-29 19:03 UTC, burunyuu23 commented on src/main/resources/db_init/init.sql
> +    patronymic    varchar NOT null,
отчество может быть null

2024-03-29 19:03 UTC, burunyuu23 commented on src/main/resources/db_init/init.sql
> +    addres       varchar NOT null,
address

2024-03-29 19:03 UTC, burunyuu23 commented on src/main/resources/db_init/init.sql
> +  FOREIGN KEY (school_id) REFERENCES school (ID)
почему ID а не id

2024-03-29 19:03 UTC, burunyuu23 commented on src/main/resources/db_init/init.sql
> +    activated BOOLEAN,
можно добавить `default false`

2024-03-30 10:32 UTC, burunyuu23 approved these changes

2024-03-31 06:44 UTC, merged